language: c++
sudo: required

before_script:
  # Add the release PGP keys:
  - curl -s https://syncthing.net/release-key.txt | sudo apt-key add -

  # Add the "release" channel to your APT sources:
  - echo "deb http://apt.syncthing.net/ syncthing release" | sudo tee /etc/apt/sources.list.d/syncthing.list

  # Update and install syncthing:
  - sudo apt-get update
  - sudo apt-get install syncthing
  
  - sudo apt-get update -qq
  - sudo apt-get install libboost-all-dev
  - sudo apt-get install fglrx opencl-headers
  
matrix:
  include:
    - os: linux
      env: COMPILER_NAME=clang CXX=clang++-3.7 CC=clang-3.7
      compiler: clang
      before_install:
        - export CC=clang-3.7
        - export CXX=clang++-3.7
        - sudo pip install codecov
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
            - g++-5
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      compiler: gcc
      before_install:
        - export CC=gcc-5
        - export CXX=g++-5
        - sudo pip install codecov
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5

cache:
  apt: true

script:
  - cmake --version
  - $CC --version
  - $CXX --version
  - mkdir build
  - cd build
  - cmake .. && make
  - ./lets_boost -s lexical_cast signals2 serialization any variant compute
  - ls -al
  - ls ../*
  - gcov main.cpp 

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false

